version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   container_name: db_mysql5.7
  #   ports:
  #     - 3336:3306
  #   environment:
  #     TZ: 'Asia/Tokyo'
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: my_database
  #   volumes:
  #     - ./db/mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: golang_blog
    tty: true
    volumes:
      - ./:/go/src
    ports:
      - 80:80
    # depends_on:
    #   - db
